-- ==========================================
-- 1. INSERT DATA KARYAWAN & JABATAN
-- ==========================================

INSERT INTO public.jabatan (id, nama) VALUES ('JAB-SUPERVISOR_PRODUKSI', 'Supervisor_Produksi') ON CONFLICT (id) DO UPDATE SET nama = EXCLUDED.nama;
INSERT INTO public.jabatan (id, nama) VALUES ('JAB-SUPERVISOR_FINISING', 'Supervisor_Finising') ON CONFLICT (id) DO UPDATE SET nama = EXCLUDED.nama;
INSERT INTO public.jabatan (id, nama) VALUES ('JAB-OPERATOR-CUTTING', 'Operator Cutting') ON CONFLICT (id) DO UPDATE SET nama = EXCLUDED.nama;
INSERT INTO public.jabatan (id, nama) VALUES ('JAB-OPERATOR-JAHIT', 'Operator Jahit') ON CONFLICT (id) DO UPDATE SET nama = EXCLUDED.nama;

INSERT INTO public.karyawan (id, nama, jabatan, gaji_pokok, aktif, tahap_list) VALUES ('KRY-001', 'Rangga Cepta Nugraha', 'JAB-SUPERVISOR_PRODUKSI', 500000, true, ARRAY[]::TEXT[]) ON CONFLICT (id) DO UPDATE SET nama = EXCLUDED.nama, jabatan = EXCLUDED.jabatan, gaji_pokok = EXCLUDED.gaji_pokok, aktif = EXCLUDED.aktif, tahap_list = EXCLUDED.tahap_list;
INSERT INTO public.karyawan (id, nama, jabatan, gaji_pokok, aktif, tahap_list) VALUES ('KRY-002', 'Hengky', 'JAB-SUPERVISOR_FINISING', 0, true, ARRAY['Lubang Kancing', 'Buang Benang', 'QC', 'Steam', 'Packing']::TEXT[]) ON CONFLICT (id) DO UPDATE SET nama = EXCLUDED.nama, jabatan = EXCLUDED.jabatan, gaji_pokok = EXCLUDED.gaji_pokok, aktif = EXCLUDED.aktif, tahap_list = EXCLUDED.tahap_list;
INSERT INTO public.karyawan (id, nama, jabatan, gaji_pokok, aktif, tahap_list) VALUES ('KRY-003', 'Abqi', 'JAB-OPERATOR-CUTTING', 0, true, ARRAY['Cutting']::TEXT[]) ON CONFLICT (id) DO UPDATE SET nama = EXCLUDED.nama, jabatan = EXCLUDED.jabatan, gaji_pokok = EXCLUDED.gaji_pokok, aktif = EXCLUDED.aktif, tahap_list = EXCLUDED.tahap_list;
INSERT INTO public.karyawan (id, nama, jabatan, gaji_pokok, aktif, tahap_list) VALUES ('KRY-004', 'Epul', 'JAB-OPERATOR-JAHIT', 0, true, ARRAY['Jahit']::TEXT[]) ON CONFLICT (id) DO UPDATE SET nama = EXCLUDED.nama, jabatan = EXCLUDED.jabatan, gaji_pokok = EXCLUDED.gaji_pokok, aktif = EXCLUDED.aktif, tahap_list = EXCLUDED.tahap_list;
INSERT INTO public.karyawan (id, nama, jabatan, gaji_pokok, aktif, tahap_list) VALUES ('KRY-005', 'Ujang Dian', 'JAB-OPERATOR-JAHIT', 0, true, ARRAY['Jahit']::TEXT[]) ON CONFLICT (id) DO UPDATE SET nama = EXCLUDED.nama, jabatan = EXCLUDED.jabatan, gaji_pokok = EXCLUDED.gaji_pokok, aktif = EXCLUDED.aktif, tahap_list = EXCLUDED.tahap_list;
INSERT INTO public.karyawan (id, nama, jabatan, gaji_pokok, aktif, tahap_list) VALUES ('KRY-006', 'Aldi', 'JAB-OPERATOR-JAHIT', 0, true, ARRAY['Jahit']::TEXT[]) ON CONFLICT (id) DO UPDATE SET nama = EXCLUDED.nama, jabatan = EXCLUDED.jabatan, gaji_pokok = EXCLUDED.gaji_pokok, aktif = EXCLUDED.aktif, tahap_list = EXCLUDED.tahap_list;
INSERT INTO public.karyawan (id, nama, jabatan, gaji_pokok, aktif, tahap_list) VALUES ('KRY-007', 'Angga', 'JAB-OPERATOR-JAHIT', 0, true, ARRAY['Jahit']::TEXT[]) ON CONFLICT (id) DO UPDATE SET nama = EXCLUDED.nama, jabatan = EXCLUDED.jabatan, gaji_pokok = EXCLUDED.gaji_pokok, aktif = EXCLUDED.aktif, tahap_list = EXCLUDED.tahap_list;
INSERT INTO public.karyawan (id, nama, jabatan, gaji_pokok, aktif, tahap_list) VALUES ('KRY-008', 'John', 'JAB-OPERATOR-JAHIT', 0, true, ARRAY['Jahit']::TEXT[]) ON CONFLICT (id) DO UPDATE SET nama = EXCLUDED.nama, jabatan = EXCLUDED.jabatan, gaji_pokok = EXCLUDED.gaji_pokok, aktif = EXCLUDED.aktif, tahap_list = EXCLUDED.tahap_list;
INSERT INTO public.karyawan (id, nama, jabatan, gaji_pokok, aktif, tahap_list) VALUES ('KRY-009', 'Ucil', 'JAB-OPERATOR-JAHIT', 0, true, ARRAY['Jahit']::TEXT[]) ON CONFLICT (id) DO UPDATE SET nama = EXCLUDED.nama, jabatan = EXCLUDED.jabatan, gaji_pokok = EXCLUDED.gaji_pokok, aktif = EXCLUDED.aktif, tahap_list = EXCLUDED.tahap_list;
INSERT INTO public.karyawan (id, nama, jabatan, gaji_pokok, aktif, tahap_list) VALUES ('KRY-010', 'Idan', 'JAB-OPERATOR-JAHIT', 0, true, ARRAY['Jahit']::TEXT[]) ON CONFLICT (id) DO UPDATE SET nama = EXCLUDED.nama, jabatan = EXCLUDED.jabatan, gaji_pokok = EXCLUDED.gaji_pokok, aktif = EXCLUDED.aktif, tahap_list = EXCLUDED.tahap_list;
INSERT INTO public.karyawan (id, nama, jabatan, gaji_pokok, aktif, tahap_list) VALUES ('KRY-011', 'Wawan', 'JAB-OPERATOR-JAHIT', 0, true, ARRAY['Jahit']::TEXT[]) ON CONFLICT (id) DO UPDATE SET nama = EXCLUDED.nama, jabatan = EXCLUDED.jabatan, gaji_pokok = EXCLUDED.gaji_pokok, aktif = EXCLUDED.aktif, tahap_list = EXCLUDED.tahap_list;
INSERT INTO public.karyawan (id, nama, jabatan, gaji_pokok, aktif, tahap_list) VALUES ('KRY-012', 'Sani', 'JAB-OPERATOR-JAHIT', 0, true, ARRAY['Jahit']::TEXT[]) ON CONFLICT (id) DO UPDATE SET nama = EXCLUDED.nama, jabatan = EXCLUDED.jabatan, gaji_pokok = EXCLUDED.gaji_pokok, aktif = EXCLUDED.aktif, tahap_list = EXCLUDED.tahap_list;
INSERT INTO public.karyawan (id, nama, jabatan, gaji_pokok, aktif, tahap_list) VALUES ('KRY-013', 'Anas', 'JAB-OPERATOR-JAHIT', 0, true, ARRAY['Jahit']::TEXT[]) ON CONFLICT (id) DO UPDATE SET nama = EXCLUDED.nama, jabatan = EXCLUDED.jabatan, gaji_pokok = EXCLUDED.gaji_pokok, aktif = EXCLUDED.aktif, tahap_list = EXCLUDED.tahap_list;
INSERT INTO public.karyawan (id, nama, jabatan, gaji_pokok, aktif, tahap_list) VALUES ('KRY-014', 'Iwan', 'JAB-OPERATOR-JAHIT', 0, true, ARRAY['Jahit']::TEXT[]) ON CONFLICT (id) DO UPDATE SET nama = EXCLUDED.nama, jabatan = EXCLUDED.jabatan, gaji_pokok = EXCLUDED.gaji_pokok, aktif = EXCLUDED.aktif, tahap_list = EXCLUDED.tahap_list;
INSERT INTO public.karyawan (id, nama, jabatan, gaji_pokok, aktif, tahap_list) VALUES ('KRY-015', 'Umar', 'JAB-OPERATOR-JAHIT', 0, true, ARRAY['Jahit']::TEXT[]) ON CONFLICT (id) DO UPDATE SET nama = EXCLUDED.nama, jabatan = EXCLUDED.jabatan, gaji_pokok = EXCLUDED.gaji_pokok, aktif = EXCLUDED.aktif, tahap_list = EXCLUDED.tahap_list;
