-- ==========================================================
-- 4. INSERT PURCHASE ORDER
-- ==========================================================

INSERT INTO public.purchase_order (id, nomor_po, klien_id, tanggal_input, tanggal_deadline, status) VALUES ('POID-PO-0001', 'PO-0001', 'KLN-001', '2026-04-16T03:36:50.130Z', '2026-04-16T03:36:50.130Z', 'aktif') ON CONFLICT (id) DO UPDATE SET nomor_po = EXCLUDED.nomor_po, klien_id = EXCLUDED.klien_id, tanggal_input = EXCLUDED.tanggal_input, tanggal_deadline = EXCLUDED.tanggal_deadline, status = EXCLUDED.status;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0001-0', 'POID-PO-0001', 'MDL-416972666C', 'WRN-008', 'SZ-S', 12, 6, 2, 'ely289', 'LYX-00040', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0001-1', 'POID-PO-0001', 'MDL-416972666C', 'WRN-008', 'SZ-M', 12, 6, 2, 'ely290', 'LYX-00041', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0001-2', 'POID-PO-0001', 'MDL-416972666C', 'WRN-008', 'SZ-L', 15, 5, 3, 'ely291', 'LYX-00042', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0001-3', 'POID-PO-0001', 'MDL-416972666C', 'WRN-008', 'SZ-XL', 15, 5, 3, 'ely292', 'LYX-00043', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0001-4', 'POID-PO-0001', 'MDL-416972666C', 'WRN-008', 'SZ-XXL', 15, 5, 3, 'ely293', 'LYX-00044', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0001-5', 'POID-PO-0001', 'MDL-416972666C', 'WRN-008', 'SZ-XXXL', 15, 5, 3, 'ely294', 'LYX-00045', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0001-6', 'POID-PO-0001', 'MDL-416972666C', 'WRN-010', 'SZ-XL', 15, 5, 3, 'ely304', 'LYX-00055', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0001-7', 'POID-PO-0001', 'MDL-416972666C', 'WRN-010', 'SZ-XXXL', 15, 5, 3, 'ely306', 'LYX-00057', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0001-8', 'POID-PO-0001', 'MDL-416972666C', 'WRN-013', 'SZ-M', 12, 6, 2, 'ely320', 'LYX-00071', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0001-9', 'POID-PO-0001', 'MDL-416972666C', 'WRN-013', 'SZ-L', 15, 5, 3, 'ely321', 'LYX-00072', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0001-10', 'POID-PO-0001', 'MDL-416972666C', 'WRN-013', 'SZ-XL', 12, 6, 2, 'ely322', 'LYX-00073', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0001-11', 'POID-PO-0001', 'MDL-416972666C', 'WRN-013', 'SZ-XXXL', 15, 5, 3, 'ely324', 'LYX-00075', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;

INSERT INTO public.purchase_order (id, nomor_po, klien_id, tanggal_input, tanggal_deadline, status) VALUES ('POID-PO-0002', 'PO-0002', 'KLN-001', '2026-04-16T03:36:50.130Z', '2026-04-16T03:36:50.130Z', 'aktif') ON CONFLICT (id) DO UPDATE SET nomor_po = EXCLUDED.nomor_po, klien_id = EXCLUDED.klien_id, tanggal_input = EXCLUDED.tanggal_input, tanggal_deadline = EXCLUDED.tanggal_deadline, status = EXCLUDED.status;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0002-0', 'POID-PO-0002', 'MDL-4E65636B', 'WRN-008', 'SZ-L', 15, 5, 3, 'ely326', 'LYX-00458', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0002-1', 'POID-PO-0002', 'MDL-4E65636B', 'WRN-008', 'SZ-XXL', 15, 5, 3, 'ely328', 'LYX-00460', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0002-2', 'POID-PO-0002', 'MDL-4E65636B', 'WRN-008', 'SZ-XXXL', 15, 5, 3, 'ely329', 'LYX-00461', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0002-3', 'POID-PO-0002', 'MDL-4E65636B', 'WRN-031', 'SZ-L', 15, 5, 3, 'ely331', 'LYX-00463', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0002-4', 'POID-PO-0002', 'MDL-4E65636B', 'WRN-031', 'SZ-XL', 15, 5, 3, 'ely332', 'LYX-00464', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0002-5', 'POID-PO-0002', 'MDL-4E65636B', 'WRN-031', 'SZ-XXL', 15, 5, 3, 'ely333', 'LYX-00465', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0002-6', 'POID-PO-0002', 'MDL-4E65636B', 'WRN-031', 'SZ-XXXL', 15, 5, 3, 'ely334', 'LYX-00466', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0002-7', 'POID-PO-0002', 'MDL-4E65636B', 'WRN-010', 'SZ-M', 12, 6, 2, 'ely335', 'LYX-00467', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0002-8', 'POID-PO-0002', 'MDL-4E65636B', 'WRN-010', 'SZ-XL', 15, 5, 3, 'ely337', 'LYX-00469', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0002-9', 'POID-PO-0002', 'MDL-4E65636B', 'WRN-010', 'SZ-XXL', 15, 5, 3, 'ely338', 'LYX-00470', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0002-10', 'POID-PO-0002', 'MDL-4E65636B', 'WRN-010', 'SZ-XXXL', 15, 5, 3, 'ely339', 'LYX-00471', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;

INSERT INTO public.purchase_order (id, nomor_po, klien_id, tanggal_input, tanggal_deadline, status) VALUES ('POID-PO-0003', 'PO-0003', 'KLN-001', '2026-04-16T03:36:50.130Z', '2026-04-16T03:36:50.130Z', 'aktif') ON CONFLICT (id) DO UPDATE SET nomor_po = EXCLUDED.nomor_po, klien_id = EXCLUDED.klien_id, tanggal_input = EXCLUDED.tanggal_input, tanggal_deadline = EXCLUDED.tanggal_deadline, status = EXCLUDED.status;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0003-0', 'POID-PO-0003', 'MDL-53746F726D', 'WRN-008', 'SZ-M', 12, 6, 2, 'ely340', 'LYX-00472', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0003-1', 'POID-PO-0003', 'MDL-53746F726D', 'WRN-008', 'SZ-L', 15, 5, 3, 'ely341', 'LYX-00473', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0003-2', 'POID-PO-0003', 'MDL-53746F726D', 'WRN-008', 'SZ-XL', 15, 5, 3, 'ely342', 'LYX-00474', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0003-3', 'POID-PO-0003', 'MDL-53746F726D', 'WRN-008', 'SZ-XXL', 15, 5, 3, 'ely343', 'LYX-00475', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0003-4', 'POID-PO-0003', 'MDL-53746F726D', 'WRN-008', 'SZ-XXXL', 15, 5, 3, 'ely344', 'LYX-00476', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0003-5', 'POID-PO-0003', 'MDL-53746F726D', 'WRN-031', 'SZ-M', 12, 6, 2, 'ely345', 'LYX-00477', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0003-6', 'POID-PO-0003', 'MDL-53746F726D', 'WRN-031', 'SZ-L', 15, 5, 3, 'ely346', 'LYX-00478', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0003-7', 'POID-PO-0003', 'MDL-53746F726D', 'WRN-031', 'SZ-XL', 15, 5, 3, 'ely347', 'LYX-00479', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0003-8', 'POID-PO-0003', 'MDL-53746F726D', 'WRN-031', 'SZ-XXL', 15, 5, 3, 'ely348', 'LYX-00480', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0003-9', 'POID-PO-0003', 'MDL-53746F726D', 'WRN-031', 'SZ-XXXL', 15, 5, 3, 'ely349', 'LYX-00481', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;

INSERT INTO public.purchase_order (id, nomor_po, klien_id, tanggal_input, tanggal_deadline, status) VALUES ('POID-PO-0004', 'PO-0004', 'KLN-001', '2026-04-16T03:36:50.130Z', '2026-04-16T03:36:50.130Z', 'aktif') ON CONFLICT (id) DO UPDATE SET nomor_po = EXCLUDED.nomor_po, klien_id = EXCLUDED.klien_id, tanggal_input = EXCLUDED.tanggal_input, tanggal_deadline = EXCLUDED.tanggal_deadline, status = EXCLUDED.status;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0004-0', 'POID-PO-0004', 'MDL-447261766F', 'WRN-008', 'SZ-M', 12, 6, 2, 'ely350', 'LYX-00261', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0004-1', 'POID-PO-0004', 'MDL-447261766F', 'WRN-008', 'SZ-L', 15, 5, 3, 'ely351', 'LYX-00262', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0004-2', 'POID-PO-0004', 'MDL-447261766F', 'WRN-008', 'SZ-XL', 15, 5, 3, 'ely352', 'LYX-00263', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0004-3', 'POID-PO-0004', 'MDL-447261766F', 'WRN-008', 'SZ-XXL', 15, 5, 3, 'ely353', 'LYX-00264', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0004-4', 'POID-PO-0004', 'MDL-447261766F', 'WRN-008', 'SZ-XXXL', 15, 5, 3, 'ely354', 'LYX-00265', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0004-5', 'POID-PO-0004', 'MDL-447261766F', 'WRN-031', 'SZ-M', 12, 6, 2, 'ely355', 'LYX-00266', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0004-6', 'POID-PO-0004', 'MDL-447261766F', 'WRN-031', 'SZ-L', 15, 5, 3, 'ely356', 'LYX-00267', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0004-7', 'POID-PO-0004', 'MDL-447261766F', 'WRN-031', 'SZ-XL', 15, 5, 3, 'ely357', 'LYX-00268', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0004-8', 'POID-PO-0004', 'MDL-447261766F', 'WRN-031', 'SZ-XXL', 15, 5, 3, 'ely358', 'LYX-00269', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0004-9', 'POID-PO-0004', 'MDL-447261766F', 'WRN-031', 'SZ-XXXL', 15, 5, 3, 'ely359', 'LYX-00270', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;

INSERT INTO public.purchase_order (id, nomor_po, klien_id, tanggal_input, tanggal_deadline, status) VALUES ('POID-PO-0005', 'PO-0005', 'KLN-001', '2026-04-16T03:36:50.130Z', '2026-04-16T03:36:50.130Z', 'aktif') ON CONFLICT (id) DO UPDATE SET nomor_po = EXCLUDED.nomor_po, klien_id = EXCLUDED.klien_id, tanggal_input = EXCLUDED.tanggal_input, tanggal_deadline = EXCLUDED.tanggal_deadline, status = EXCLUDED.status;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0005-0', 'POID-PO-0005', 'MDL-5A756E6F20', 'WRN-008', 'SZ-XXXL', 12, 6, 2, 'ely492', 'LYX-00619', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0005-1', 'POID-PO-0005', 'MDL-5A756E6F20', 'WRN-046', 'SZ-XXL', 12, 6, 2, 'ely497', 'LYX-00624', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0005-2', 'POID-PO-0005', 'MDL-5A756E6F20', 'WRN-046', 'SZ-XXXL', 12, 6, 2, 'ely498', 'LYX-00625', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0005-3', 'POID-PO-0005', 'MDL-5A756E6F20', 'WRN-008', 'SZ-XXL', 10, 5, 2, 'ely515', 'LYX-00642', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0005-4', 'POID-PO-0005', 'MDL-5A756E6F20', 'WRN-012', 'SZ-XXL', 10, 5, 2, 'ely533', 'LYX-00660', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;

INSERT INTO public.purchase_order (id, nomor_po, klien_id, tanggal_input, tanggal_deadline, status) VALUES ('POID-PO-0006', 'PO-0006', 'KLN-001', '2026-04-16T03:36:50.130Z', '2026-04-16T03:36:50.130Z', 'aktif') ON CONFLICT (id) DO UPDATE SET nomor_po = EXCLUDED.nomor_po, klien_id = EXCLUDED.klien_id, tanggal_input = EXCLUDED.tanggal_input, tanggal_deadline = EXCLUDED.tanggal_deadline, status = EXCLUDED.status;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0006-0', 'POID-PO-0006', 'MDL-48696E6F20', 'WRN-046', 'SZ-XXXL', 12, 6, 2, 'ely546', 'LYX-00359', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0006-1', 'POID-PO-0006', 'MDL-48696E6F20', 'WRN-012', 'SZ-L', 12, 6, 2, 'ely555', 'LYX-00368', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0006-2', 'POID-PO-0006', 'MDL-48696E6F20', 'WRN-012', 'SZ-XL', 12, 6, 2, 'ely556', 'LYX-00369', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0006-3', 'POID-PO-0006', 'MDL-48696E6F20', 'WRN-012', 'SZ-XXXL', 10, 5, 2, 'ely582', 'LYX-00395', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;

INSERT INTO public.purchase_order (id, nomor_po, klien_id, tanggal_input, tanggal_deadline, status) VALUES ('POID-PO-0007', 'PO-0007', 'KLN-001', '2026-04-16T03:36:50.130Z', '2026-04-16T03:36:50.130Z', 'aktif') ON CONFLICT (id) DO UPDATE SET nomor_po = EXCLUDED.nomor_po, klien_id = EXCLUDED.klien_id, tanggal_input = EXCLUDED.tanggal_input, tanggal_deadline = EXCLUDED.tanggal_deadline, status = EXCLUDED.status;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0007-0', 'POID-PO-0007', 'MDL-4A696D6F20', 'WRN-008', 'SZ-S', 10, 5, 2, 'ely583', 'LYX-00396', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0007-1', 'POID-PO-0007', 'MDL-4A696D6F20', 'WRN-046', 'SZ-S', 10, 5, 2, 'ely589', 'LYX-00402', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0007-2', 'POID-PO-0007', 'MDL-4A696D6F20', 'WRN-046', 'SZ-L', 12, 6, 2, 'ely591', 'LYX-00404', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0007-3', 'POID-PO-0007', 'MDL-4A696D6F20', 'WRN-012', 'SZ-S', 10, 5, 2, 'ely601', 'LYX-00414', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0007-4', 'POID-PO-0007', 'MDL-4A696D6F20', 'WRN-012', 'SZ-M', 10, 5, 2, 'ely602', 'LYX-00415', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;

INSERT INTO public.purchase_order (id, nomor_po, klien_id, tanggal_input, tanggal_deadline, status) VALUES ('POID-PO-0008', 'PO-0008', 'KLN-001', '2026-04-16T03:36:50.130Z', '2026-04-16T03:36:50.130Z', 'aktif') ON CONFLICT (id) DO UPDATE SET nomor_po = EXCLUDED.nomor_po, klien_id = EXCLUDED.klien_id, tanggal_input = EXCLUDED.tanggal_input, tanggal_deadline = EXCLUDED.tanggal_deadline, status = EXCLUDED.status;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0008-0', 'POID-PO-0008', 'MDL-4173686572', 'WRN-029', 'SZ-M', 6, 6, 1, 'ely386', 'LYX-00214', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0008-1', 'POID-PO-0008', 'MDL-4173686572', 'WRN-029', 'SZ-L', 6, 6, 1, 'ely387', 'LYX-00215', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0008-2', 'POID-PO-0008', 'MDL-4173686572', 'WRN-029', 'SZ-XL', 6, 6, 1, 'ely388', 'LYX-00216', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0008-3', 'POID-PO-0008', 'MDL-4173686572', 'WRN-029', 'SZ-XXL', 6, 6, 1, 'ely389', 'LYX-00217', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0008-4', 'POID-PO-0008', 'MDL-4173686572', 'WRN-029', 'SZ-XXXL', 6, 6, 1, 'ely390', 'LYX-00218', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0008-5', 'POID-PO-0008', 'MDL-4173686572', 'WRN-015', 'SZ-XXL', 6, 6, 1, 'ely395', 'LYX-00223', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0008-6', 'POID-PO-0008', 'MDL-4173686572', 'WRN-030', 'SZ-M', 6, 6, 1, 'ely398', 'LYX-00226', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0008-7', 'POID-PO-0008', 'MDL-4173686572', 'WRN-030', 'SZ-XL', 6, 6, 1, 'ely400', 'LYX-00228', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0008-8', 'POID-PO-0008', 'MDL-4173686572', 'WRN-030', 'SZ-XXL', 6, 6, 1, 'ely401', 'LYX-00229', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;

INSERT INTO public.purchase_order (id, nomor_po, klien_id, tanggal_input, tanggal_deadline, status) VALUES ('POID-PO-0009', 'PO-0009', 'KLN-001', '2026-04-16T03:36:50.130Z', '2026-04-16T03:36:50.130Z', 'aktif') ON CONFLICT (id) DO UPDATE SET nomor_po = EXCLUDED.nomor_po, klien_id = EXCLUDED.klien_id, tanggal_input = EXCLUDED.tanggal_input, tanggal_deadline = EXCLUDED.tanggal_deadline, status = EXCLUDED.status;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0009-0', 'POID-PO-0009', 'MDL-417264656E', 'WRN-014', 'SZ-XL', 6, 6, 1, 'ely412', 'LYX-00138', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;

INSERT INTO public.purchase_order (id, nomor_po, klien_id, tanggal_input, tanggal_deadline, status) VALUES ('POID-PO-0010', 'PO-0010', 'KLN-001', '2026-04-16T03:36:50.130Z', '2026-04-16T03:36:50.130Z', 'aktif') ON CONFLICT (id) DO UPDATE SET nomor_po = EXCLUDED.nomor_po, klien_id = EXCLUDED.klien_id, tanggal_input = EXCLUDED.tanggal_input, tanggal_deadline = EXCLUDED.tanggal_deadline, status = EXCLUDED.status;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0010-0', 'POID-PO-0010', 'MDL-547269636F', 'WRN-044', 'SZ-M', 6, 6, 1, 'ely422', 'LYX-00523', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0010-1', 'POID-PO-0010', 'MDL-547269636F', 'WRN-044', 'SZ-XL', 6, 6, 1, 'ely424', 'LYX-00525', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0010-2', 'POID-PO-0010', 'MDL-547269636F', 'WRN-044', 'SZ-XXL', 6, 6, 1, 'ely425', 'LYX-00526', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0010-3', 'POID-PO-0010', 'MDL-547269636F', 'WRN-054', 'SZ-M', 6, 6, 1, 'ely428', 'LYX-00529', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0010-4', 'POID-PO-0010', 'MDL-547269636F', 'WRN-054', 'SZ-XXXL', 6, 6, 1, 'ely432', 'LYX-00533', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;

INSERT INTO public.purchase_order (id, nomor_po, klien_id, tanggal_input, tanggal_deadline, status) VALUES ('POID-PO-0011', 'PO-0011', 'KLN-001', '2026-04-16T03:36:50.130Z', '2026-04-16T03:36:50.130Z', 'aktif') ON CONFLICT (id) DO UPDATE SET nomor_po = EXCLUDED.nomor_po, klien_id = EXCLUDED.klien_id, tanggal_input = EXCLUDED.tanggal_input, tanggal_deadline = EXCLUDED.tanggal_deadline, status = EXCLUDED.status;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0011-0', 'POID-PO-0011', 'MDL-4865726974', 'WRN-043', 'SZ-S', 6, 6, 1, 'ely439', 'LYX-00300', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0011-1', 'POID-PO-0011', 'MDL-4865726974', 'WRN-044', 'SZ-M', 6, 6, 1, 'ely440', 'LYX-00301', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0011-2', 'POID-PO-0011', 'MDL-4865726974', 'WRN-044', 'SZ-L', 6, 6, 1, 'ely441', 'LYX-00302', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0011-3', 'POID-PO-0011', 'MDL-4865726974', 'WRN-044', 'SZ-XL', 6, 6, 1, 'ely442', 'LYX-00303', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0011-4', 'POID-PO-0011', 'MDL-4865726974', 'WRN-044', 'SZ-XXL', 6, 6, 1, 'ely443', 'LYX-00304', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0011-5', 'POID-PO-0011', 'MDL-4865726974', 'WRN-044', 'SZ-XXXL', 6, 6, 1, 'ely444', 'LYX-00305', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0011-6', 'POID-PO-0011', 'MDL-4865726974', 'WRN-008', 'SZ-M', 6, 6, 1, 'ely446', 'LYX-00307', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0011-7', 'POID-PO-0011', 'MDL-4865726974', 'WRN-008', 'SZ-XXL', 6, 6, 1, 'ely449', 'LYX-00310', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0011-8', 'POID-PO-0011', 'MDL-4865726974', 'WRN-031', 'SZ-XL', 6, 6, 1, 'ely454', 'LYX-00315', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0011-9', 'POID-PO-0011', 'MDL-4865726974', 'WRN-031', 'SZ-XXL', 6, 6, 1, 'ely455', 'LYX-00316', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0011-10', 'POID-PO-0011', 'MDL-4865726974', 'WRN-031', 'SZ-XXXL', 6, 6, 1, 'ely456', 'LYX-00317', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0011-11', 'POID-PO-0011', 'MDL-4865726974', 'WRN-045', 'SZ-L', 6, 6, 1, 'ely459', 'LYX-00320', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0011-12', 'POID-PO-0011', 'MDL-4865726974', 'WRN-045', 'SZ-XXXL', 6, 6, 1, 'ely462', 'LYX-00323', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;

INSERT INTO public.purchase_order (id, nomor_po, klien_id, tanggal_input, tanggal_deadline, status) VALUES ('POID-PO-0012', 'PO-0012', 'KLN-001', '2026-04-16T03:36:50.130Z', '2026-04-16T03:36:50.130Z', 'aktif') ON CONFLICT (id) DO UPDATE SET nomor_po = EXCLUDED.nomor_po, klien_id = EXCLUDED.klien_id, tanggal_input = EXCLUDED.tanggal_input, tanggal_deadline = EXCLUDED.tanggal_deadline, status = EXCLUDED.status;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0012-0', 'POID-PO-0012', 'MDL-4865726974', 'WRN-044', 'SZ-M', 6, 6, 1, 'ely464', 'LYX-00325', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0012-1', 'POID-PO-0012', 'MDL-4865726974', 'WRN-044', 'SZ-L', 6, 6, 1, 'ely465', 'LYX-00326', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0012-2', 'POID-PO-0012', 'MDL-4865726974', 'WRN-044', 'SZ-XL', 6, 6, 1, 'ely466', 'LYX-00327', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0012-3', 'POID-PO-0012', 'MDL-4865726974', 'WRN-044', 'SZ-XXL', 6, 6, 1, 'ely467', 'LYX-00328', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0012-4', 'POID-PO-0012', 'MDL-4865726974', 'WRN-044', 'SZ-XXXL', 6, 6, 1, 'ely468', 'LYX-00329', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0012-5', 'POID-PO-0012', 'MDL-4865726974', 'WRN-008', 'SZ-L', 6, 6, 1, 'ely471', 'LYX-00332', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0012-6', 'POID-PO-0012', 'MDL-4865726974', 'WRN-008', 'SZ-XL', 6, 6, 1, 'ely472', 'LYX-00333', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0012-7', 'POID-PO-0012', 'MDL-4865726974', 'WRN-008', 'SZ-XXL', 6, 6, 1, 'ely473', 'LYX-00334', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0012-8', 'POID-PO-0012', 'MDL-4865726974', 'WRN-008', 'SZ-XXXL', 6, 6, 1, 'ely474', 'LYX-00335', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0012-9', 'POID-PO-0012', 'MDL-4865726974', 'WRN-031', 'SZ-M', 6, 6, 1, 'ely476', 'LYX-00337', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0012-10', 'POID-PO-0012', 'MDL-4865726974', 'WRN-031', 'SZ-XL', 6, 6, 1, 'ely478', 'LYX-00339', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0012-11', 'POID-PO-0012', 'MDL-4865726974', 'WRN-031', 'SZ-XXL', 6, 6, 1, 'ely479', 'LYX-00340', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0012-12', 'POID-PO-0012', 'MDL-4865726974', 'WRN-031', 'SZ-XXXL', 6, 6, 1, 'ely480', 'LYX-00341', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0012-13', 'POID-PO-0012', 'MDL-4865726974', 'WRN-045', 'SZ-XL', 6, 6, 1, 'ely484', 'LYX-00345', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0012-14', 'POID-PO-0012', 'MDL-4865726974', 'WRN-045', 'SZ-XXL', 6, 6, 1, 'ely485', 'LYX-00346', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0012-15', 'POID-PO-0012', 'MDL-4865726974', 'WRN-045', 'SZ-XXXL', 6, 6, 1, 'ely486', 'LYX-00347', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;

INSERT INTO public.purchase_order (id, nomor_po, klien_id, tanggal_input, tanggal_deadline, status) VALUES ('POID-PO-0013', 'PO-0013', 'KLN-001', '2026-04-16T03:36:50.130Z', '2026-04-16T03:36:50.130Z', 'aktif') ON CONFLICT (id) DO UPDATE SET nomor_po = EXCLUDED.nomor_po, klien_id = EXCLUDED.klien_id, tanggal_input = EXCLUDED.tanggal_input, tanggal_deadline = EXCLUDED.tanggal_deadline, status = EXCLUDED.status;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0013-0', 'POID-PO-0013', 'MDL-4172736C61', 'WRN-006', 'SZ-S', 4, 4, 1, 'ely01', 'LYX-00177', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0013-1', 'POID-PO-0013', 'MDL-4172736C61', 'WRN-006', 'SZ-M', 6, 6, 1, 'ely02', 'LYX-00178', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0013-2', 'POID-PO-0013', 'MDL-4172736C61', 'WRN-025', 'SZ-M', 6, 6, 1, 'ely08', 'LYX-00184', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0013-3', 'POID-PO-0013', 'MDL-4172736C61', 'WRN-025', 'SZ-XXXL', 10, 10, 1, 'ely12', 'LYX-00188', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0013-4', 'POID-PO-0013', 'MDL-4172736C61', 'WRN-017', 'SZ-M', 15, 15, 1, 'ely14', 'LYX-00190', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0013-5', 'POID-PO-0013', 'MDL-4172736C61', 'WRN-017', 'SZ-XL', 10, 10, 1, 'ely16', 'LYX-00192', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;

INSERT INTO public.purchase_order (id, nomor_po, klien_id, tanggal_input, tanggal_deadline, status) VALUES ('POID-PO-0014', 'PO-0014', 'KLN-001', '2026-04-16T03:36:50.130Z', '2026-04-16T03:36:50.130Z', 'aktif') ON CONFLICT (id) DO UPDATE SET nomor_po = EXCLUDED.nomor_po, klien_id = EXCLUDED.klien_id, tanggal_input = EXCLUDED.tanggal_input, tanggal_deadline = EXCLUDED.tanggal_deadline, status = EXCLUDED.status;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0014-0', 'POID-PO-0014', 'MDL-4B68616C69', 'WRN-050', 'SZ-XXXL', 10, 10, 1, 'ely96', 'LYX-00456', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;

INSERT INTO public.purchase_order (id, nomor_po, klien_id, tanggal_input, tanggal_deadline, status) VALUES ('POID-PO-0015', 'PO-0015', 'KLN-001', '2026-04-16T03:36:50.130Z', '2026-04-16T03:36:50.130Z', 'aktif') ON CONFLICT (id) DO UPDATE SET nomor_po = EXCLUDED.nomor_po, klien_id = EXCLUDED.klien_id, tanggal_input = EXCLUDED.tanggal_input, tanggal_deadline = EXCLUDED.tanggal_deadline, status = EXCLUDED.status;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0015-0', 'POID-PO-0015', 'MDL-48696E6F20', 'WRN-008', 'SZ-M', 10, 10, 1, 'ely536', 'LYX-00349', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0015-1', 'POID-PO-0015', 'MDL-48696E6F20', 'WRN-008', 'SZ-XL', 10, 10, 1, 'ely538', 'LYX-00351', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0015-2', 'POID-PO-0015', 'MDL-48696E6F20', 'WRN-008', 'SZ-XXL', 10, 10, 1, 'ely539', 'LYX-00352', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;

INSERT INTO public.purchase_order (id, nomor_po, klien_id, tanggal_input, tanggal_deadline, status) VALUES ('POID-PO-0016', 'PO-0016', 'KLN-001', '2026-04-16T03:36:50.130Z', '2026-04-16T03:36:50.130Z', 'aktif') ON CONFLICT (id) DO UPDATE SET nomor_po = EXCLUDED.nomor_po, klien_id = EXCLUDED.klien_id, tanggal_input = EXCLUDED.tanggal_input, tanggal_deadline = EXCLUDED.tanggal_deadline, status = EXCLUDED.status;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0016-0', 'POID-PO-0016', 'MDL-43656C616E', 'WRN-031', 'SZ-XL', 20, 20, 1, 'ely268', 'LYX-00240', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0016-1', 'POID-PO-0016', 'MDL-43656C616E', 'WRN-032', 'SZ-XXL', 20, 20, 1, 'ely275', 'LYX-00247', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0016-2', 'POID-PO-0016', 'MDL-43656C616E', 'WRN-008', 'SZ-L', 10, 10, 1, 'ely261', 'LYX-00233', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0016-3', 'POID-PO-0016', 'MDL-43656C616E', 'WRN-008', 'SZ-XXXL', 10, 10, 1, 'ely264', 'LYX-00236', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;

INSERT INTO public.purchase_order (id, nomor_po, klien_id, tanggal_input, tanggal_deadline, status) VALUES ('POID-PO-0017', 'PO-0017', 'KLN-001', '2026-04-16T03:36:50.130Z', '2026-04-16T03:36:50.130Z', 'aktif') ON CONFLICT (id) DO UPDATE SET nomor_po = EXCLUDED.nomor_po, klien_id = EXCLUDED.klien_id, tanggal_input = EXCLUDED.tanggal_input, tanggal_deadline = EXCLUDED.tanggal_deadline, status = EXCLUDED.status;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0017-0', 'POID-PO-0017', 'MDL-416275647A', 'WRN-002', 'SZ-XXL', 5, 5, 1, 'ely157', 'LYX-00011', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0017-1', 'POID-PO-0017', 'MDL-416275647A', 'WRN-002', 'SZ-XXXL', 5, 5, 1, 'ely158', 'LYX-00012', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;

INSERT INTO public.purchase_order (id, nomor_po, klien_id, tanggal_input, tanggal_deadline, status) VALUES ('POID-PO-0018', 'PO-0018', 'KLN-001', '2026-04-16T03:36:50.130Z', '2026-04-16T03:36:50.130Z', 'aktif') ON CONFLICT (id) DO UPDATE SET nomor_po = EXCLUDED.nomor_po, klien_id = EXCLUDED.klien_id, tanggal_input = EXCLUDED.tanggal_input, tanggal_deadline = EXCLUDED.tanggal_deadline, status = EXCLUDED.status;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0018-0', 'POID-PO-0018', 'MDL-4E65636B', 'WRN-008', 'SZ-XL', 5, 5, 1, 'ely327', 'LYX-00459', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0018-1', 'POID-PO-0018', 'MDL-416972666C', 'WRN-013', 'SZ-XXL', 5, 5, 1, 'ely323', 'LYX-00074', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0018-2', 'POID-PO-0018', 'MDL-416972666C', 'WRN-010', 'SZ-XXL', 5, 5, 1, 'ely305', 'LYX-00056', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;

INSERT INTO public.purchase_order (id, nomor_po, klien_id, tanggal_input, tanggal_deadline, status) VALUES ('POID-PO-0019', 'PO-0019', 'KLN-001', '2026-04-16T03:36:50.130Z', '2026-04-16T03:36:50.130Z', 'aktif') ON CONFLICT (id) DO UPDATE SET nomor_po = EXCLUDED.nomor_po, klien_id = EXCLUDED.klien_id, tanggal_input = EXCLUDED.tanggal_input, tanggal_deadline = EXCLUDED.tanggal_deadline, status = EXCLUDED.status;
INSERT INTO public.po_item (id, po_id, model_id, warna_id, size_id, qty, qty_per_bundle, jumlah_bundle, sku_klien, sku_internal, status_cutting) VALUES ('POI-POID-PO-0019-0', 'POID-PO-0019', 'MDL-48696E6F20', 'WRN-008', 'SZ-XXXL', 12, 12, 1, 'ely540', 'LYX-00353', 'waiting') ON CONFLICT (id) DO UPDATE SET qty = EXCLUDED.qty, qty_per_bundle = EXCLUDED.qty_per_bundle, jumlah_bundle = EXCLUDED.jumlah_bundle;

